### ISSUE TITLE
[feature request] Please provide `BSD` variant detection

### ISSUE THREAD

**Issue by krishnakumarg1984** [wspr/will2e#3]
Would you consider providing detection of various `bsd` variants?

* freebsd
* openbsd
* dragonflybsd
* netbsd
* illumos

**Comment by wspr** [comment]
Can you suggest robust ways that these could be detected?
E.g., for macOS there has been a suggestion we should add a test for a file such as 

    /System/Library/Fonts/Monaco.dfont

I wouldn’t want to provide variants for every flavour of BSD but if you an propose a way that I could differentiate between Linux and BSD I’d be happy to add something.

If you simply want to branch based on `uname` it might be better just to follow the example given in the documentation.

Cheers,
Will

**Comment by krishnakumarg1984** [comment]
Apart from `uname`, you could also read the string in the file `cat /etc/*version`


But `uname` based detection seems to be the most common way to do this.

https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script?rq=1 
https://superuser.com/questions/649731/how-do-you-determine-if-youre-on-a-linux-or-bsd-system-inside-a-script
https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script

**Comment by wspr** [comment]
I would rather not rely on external tools as by default shell escape isn’t enabled. I need to update the macOS detection to the file check...
